version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_URL: 'postgresql://postgres:1234@database:5432/tsp?schema=public'
      PORT: 3000
      SECRET_SAUCE: 'hastalavista'
    ports:
      - '3000:3000'

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '4173:4173'
    restart: always
    environment:
      - VITE_API_URL=http://backend:3000

  database:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tsp
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
